/**
 * BẢNG MA TRẬN PHÂN QUYỀN THAO TÁC TRONG BASE ACCOUNT (BASE.VN)
 * Tham chiếu tài liệu chính thức: https://help.base.vn/support/solutions/articles/63000273376
 * Chú giải:
 * 'yes'         : Mặc định có quyền (✓)
 * 'no'          : Mặc định Không có quyền (✗)
 * 'key'         : Được làm nếu phân quyền (🔑)
 * 'self'        : Chính mình
 * 'group_owner' : Là owner nhóm đó
 */

const BASE_OPERATION_PERMISSIONS = [
  // PHÂN HỆ 1: TÀI KHOẢN (15 thao tác)
  {
    id: 'acc_create_direct',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Tạo TK trực tiếp',
    description: 'Thêm tài khoản nhân sự mới trực tiếp trên hệ thống',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_create_excel',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Tạo TK từ excel',
    description: 'Nhập danh sách tài khoản hàng loạt từ tệp Excel/CSV',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_update_excel',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Cập nhật thông tin TK từ excel',
    description: 'Đồng bộ và ghi đè thông tin tài khoản hàng loạt qua Excel',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_export_excel',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Xuất danh sách TK ra excel',
    description: 'Tải danh bạ tài khoản toàn doanh nghiệp về máy',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_change_role',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Thay đổi quyền owner/ admin/ member',
    description: 'Nâng cấp hoặc hạ bậc vai trò quản trị hệ thống',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'acc_change_email',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Thay đổi email TK',
    description: 'Đổi địa chỉ email đăng nhập của nhân sự (Cần ủy quyền đặc biệt)',
    owner: 'yes',
    appAdmin: 'key',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'acc_change_password',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Thay đổi mật khẩu TK',
    description: 'Cấp lại hoặc đổi mật khẩu tài khoản',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'self',
  },
  {
    id: 'acc_edit_info',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Chỉnh sửa thông tin TK',
    description: 'Sửa họ tên, số điện thoại, chức danh, phòng ban',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_edit_manager',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Chỉnh sửa quản lý trực tiếp',
    description: 'Gán hoặc đổi người duyệt và quản lý cấp trên (Direct Manager)',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'acc_edit_lang',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Chỉnh sửa ngôn ngữ',
    description: 'Thay đổi ngôn ngữ hiển thị giao diện Tiếng Việt / Tiếng Anh',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'self',
  },
  {
    id: 'acc_edit_schedule',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Chỉnh sửa lịch làm việc',
    description: 'Cấu hình thời gian làm việc chuẩn và ngày nghỉ',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'self',
  },
  {
    id: 'acc_2fa',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Cài đặt bảo mật hai lớp',
    description: 'Bật/tắt 2FA xác thực hai bước',
    owner: 'yes',
    appAdmin: 'self',
    admin: 'self',
    member: 'self',
  },
  {
    id: 'acc_disable_message',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Tắt ứng dụng Base Message',
    description: 'Ngắt truy cập kênh chat tin nhắn nội bộ',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'acc_deactivate',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Vô hiệu hóa TK',
    description: 'Khóa tài khoản và thu hồi toàn bộ token truy cập',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'acc_reactivate',
    module: 'account',
    moduleName: 'Tài khoản',
    action: 'Kích hoạt lại TK',
    description: 'Mở khóa tài khoản đã bị vô hiệu hóa',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },

  // PHÂN HỆ 2: NHÓM (8 thao tác)
  {
    id: 'grp_add',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Thêm nhóm',
    description: 'Tạo phòng ban hoặc nhóm làm việc mới',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'grp_edit_info',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Chỉnh sửa thông tin nhóm',
    description: 'Cập nhật tên nhóm, mô tả, cơ cấu',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_add_member',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Thêm thành viên vào nhóm',
    description: 'Bổ sung nhân sự vào phòng ban/nhóm',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_change_perm',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Thay đổi quyền quản lý/ quản trị của nhóm',
    description: 'Chỉ định trưởng phòng/trưởng nhóm',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_set_schedule',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Cài đặt lịch làm việc cho nhóm',
    description: 'Thiết lập ca làm việc và lịch biểu nhóm',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_export_members',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Xuất danh sách thành viên trong nhóm',
    description: 'Xuất danh sách nhân sự của phòng ban',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_remove_member',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Xóa thành viên ra khỏi nhóm',
    description: 'Loại nhân sự ra khỏi nhóm làm việc',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'group_owner',
    member: 'no',
  },
  {
    id: 'grp_delete',
    module: 'groups',
    moduleName: 'Nhóm',
    action: 'Xóa nhóm',
    description: 'Giải tán phòng ban hoặc nhóm làm việc',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },

  // PHÂN HỆ 3: TK KHÁCH (7 thao tác)
  {
    id: 'guest_create',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Tạo TK khách',
    description: 'Tạo tài khoản Guest cho đối tác, khách hàng xem tiến độ',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'no',
  },
  {
    id: 'guest_edit',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Chỉnh sửa TK khách',
    description: 'Cập nhật thông tin nhận diện tài khoản khách',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'guest_change_email',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Thay đổi email TK khách',
    description: 'Đổi email đăng nhập của khách',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'guest_change_pw',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Thay đổi mật khẩu TK khách',
    description: 'Cấp lại mật khẩu cho tài khoản khách',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'guest_perm_wework',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Phân quyền truy cập vào Wework',
    description: 'Cấp quyền cho khách vào dự án cụ thể',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'guest_disable_msg',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Tắt ứng dụng Base Message',
    description: 'Chặn tin nhắn đối với tài khoản khách',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'guest_deactivate',
    module: 'guest',
    moduleName: 'TK khách',
    action: 'Vô hiệu hóa TK',
    description: 'Khóa tài khoản khách',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },

  // PHÂN HỆ 4: ỨNG DỤNG (2 thao tác)
  {
    id: 'app_manage_admin',
    module: 'apps',
    moduleName: 'Ứng dụng',
    action: 'Quản lý admin ứng dụng',
    description: 'Chỉ định tài khoản làm App Admin cho từng ứng dụng',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'app_manage_members',
    module: 'apps',
    moduleName: 'Ứng dụng',
    action: 'Quản lý thành viên',
    description: 'Thêm/bớt người dùng được phép sử dụng ứng dụng',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },

  // PHÂN HỆ 5: TÙY CHỈNH NÂNG CAO (6 thao tác)
  {
    id: 'adv_login_history',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Lịch sử đăng nhập',
    description: 'Xem nhật ký thời gian và IP đăng nhập',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'yes',
  },
  {
    id: 'adv_device_manage',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Quản lý thiết bị',
    description: 'Xem thiết bị đang đăng nhập và đăng xuất từ xa',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'yes',
  },
  {
    id: 'adv_email_notif',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Tùy chỉnh email thông báo',
    description: 'Bật/tắt nhận thông báo qua email',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'yes',
  },
  {
    id: 'adv_timezone',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Chỉnh sửa múi giờ',
    description: 'Cài đặt múi giờ làm việc chuẩn (GMT+7)',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'yes',
  },
  {
    id: 'adv_delegation',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Ủy quyền tạm thời',
    description: 'Ủy quyền xử lý công việc khi đi công tác/nghỉ phép',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'yes',
    member: 'yes',
  },
  {
    id: 'adv_edit_perm',
    module: 'advanced',
    moduleName: 'Tùy chỉnh nâng cao',
    action: 'Quyền chỉnh sửa thông tin',
    description: 'Phân quyền ai được sửa trường thông tin mở rộng',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },

  // PHÂN HỆ 6: ỨNG DỤNG VÀ BẢO MẬT (7 thao tác)
  {
    id: 'sec_ip_whitelist',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Bảo mật theo dải IP',
    description: 'Giới hạn chỉ cho phép truy cập từ dải IP văn phòng',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_edit_company',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Chỉnh sửa công ty',
    description: 'Sửa tên doanh nghiệp, logo, thông tin pháp nhân',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_view_perm',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Quyền xem thông tin',
    description: 'Quy định quyền xem danh bạ và dữ liệu cá nhân đồng nghiệp',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_audit_logs',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Logs hệ thống',
    description: 'Toàn bộ vết hoạt động và truy vết kiểm toán bảo mật',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_third_party',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Tích hợp với bên thứ ba',
    description: 'Webhooks, API Tokens, liên kết phần mềm ngoài',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_root_block',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'Cho phép sử dụng app Base trên thiết bị di động đã root',
    description: 'Chặn thiết bị di động không bảo mật đã can thiệp root/jailbreak',
    owner: 'yes',
    appAdmin: 'no',
    admin: 'no',
    member: 'no',
  },
  {
    id: 'sec_saml_sso',
    module: 'security',
    moduleName: 'Ứng dụng và bảo mật',
    action: 'SAML',
    description: 'Cấu hình đăng nhập một lần doanh nghiệp SAML 2.0 / SSO',
    owner: 'yes',
    appAdmin: 'yes',
    admin: 'no',
    member: 'no',
  },
];

const BASE_APPS_CATALOG = [
  {
    key: 'work',
    code: 'BASE_WORK',
    name: 'Base Work+',
    tagline: 'Quản lý Dự án & Tiến độ Phân bổ Công việc',
    color: '#2563eb',
    defaultAdminRole: 'project_manager',
  },
  {
    key: 'schedule',
    code: 'BASE_SCHEDULE',
    name: 'Base Schedule+',
    tagline: 'Lịch Làm việc Đa góc nhìn (Ngày/Tuần/Tháng)',
    color: '#10b981',
    defaultAdminRole: 'project_manager',
  },
  {
    key: 'optimize',
    code: 'BASE_OPTIMIZE',
    name: 'Base Optimize+',
    tagline: 'Thuật toán Tối ưu Nguồn lực Tự động (GA/CSP/Hybrid)',
    color: '#8b5cf6',
    defaultAdminRole: 'admin',
  },
  {
    key: 'analytics',
    code: 'BASE_ANALYTICS',
    name: 'Base Analytics+',
    tagline: 'Báo cáo Chuyên sâu, Đo lường FTE & Cảnh báo Burnout',
    color: '#f59e0b',
    defaultAdminRole: 'admin',
  },
  {
    key: 'resource',
    code: 'BASE_RESOURCE',
    name: 'Base Resource+',
    tagline: 'Hồ sơ Kỹ năng Nhân sự & Định mức Tải',
    color: '#06b6d4',
    defaultAdminRole: 'admin',
  },
];

module.exports = {
  BASE_OPERATION_PERMISSIONS,
  BASE_APPS_CATALOG,
};
